### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by zirgeliins** [maxlotz/TF_DD2427Proj#1]
Hey! I've been trying to run your script and model what you've been doing with tiny imagenet on my own dataset. Picked your model because you've commented it so well, so I thought as a beginner at tf this was a great help. I ran into a couple of issues, that triggered me to run your script with the original dataset but again - no success. 
Here's what I did. Downloaded the tiny imagenet, changed the paths in your label_creator script (didn't change cnn.py at all) and ran both in python 2.7 (conda env). label_creator.py ran without issues. However, I got this error upon running the cnn.py:

W tensorflow/core/framework/op_kernel.cc:940] Not found: p/Users/username/python/tinyimg/tiny-imagenet-200/train/n04398044/images/n04398044_54.JPEG
Traceback (most recent call last):
  File "cnn.py", line 272, in <module>
    _, summary, loss_ = sess.run([train_step, summary_op, loss])
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.OutOfRangeError: RandomShuffleQueue '_1_input/shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 25, current size 0)
	 [[Node: input/shuffle_batch = QueueDequeueMany[_class=["loc:@input/shuffle_batch/random_shuffle_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input/shuffle_batch/random_shuffle_queue, input/shuffle_batch/n)]]
Caused by op u'input/shuffle_batch', defined at:
  File "cnn.py", line 150, in <module>
    train_image_batch, train_label_batch = input_pipeline(train_images, train_labels)
  File "cnn.py", line 86, in input_pipeline
    min_after_dequeue=MIN_AFTER_DEQUEUE,
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 817, in shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 435, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 867, in _queue_dequeue_many
    timeout_ms=timeout_ms, name=name)
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/username/anaconda/envs/2.7env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

This pretty much mirrored the errors Iv''e been getting with my own dataset too. Not familiar with tensorflow at all.  Any clue what this might be about?

**Comment by zirgeliins** [comment]
Solved it - was just a small typo. Runs like charm!
